name: Ditto Social
favicon: null
layout_spectrum: 0.22252018237486482
typography_spectrum: 0.21801358135417104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6184336659498513
  lightness: 0.5127068811561912
  saturation: 0.6538836958352476
  rhythmicContrast: 0.30268537369556725
purpose: []
