name: Ditto Social
favicon: null
layout_spectrum: 0
typography_spectrum: 0.41896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0069b5'
    - '#e14e42'
    - '#6aa8db'
    - '#000000'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
