name: Ditto Social
favicon: null
layout_spectrum: 0
typography_spectrum: 0.44517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2876b8'
    - '#b5d0e6'
    - '#d3e3f0'
    - '#86b2d7'
  brandStrength: 1
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 1
purpose: []
