name: Ditto Social
favicon: null
layout_spectrum: 0.22252018237486482
typography_spectrum: 0.21801358135417104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0069b5'
    - '#e14e42'
    - '#6aa8db'
    - '#000000'
  brandStrength: 0.6184336659498513
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
